# adds the bin directories for git and drush
export PATH=/usr/local/bin:/usr/local/sbin:~/bin:/Applications/MAMP/Library/bin:$PATH

# Shuts off homebrew analytics
export HOMEBREW_NO_ANALYTICS=1

# Properly formats the command line interface
GREEN="\[$(tput setaf 2)\]"
RESET="\[$(tput sgr0)\]"

export PS1="\n${GREEN}\w${RESET}\n$ "

# Setup auto completion for text
if [ -f ~/Dropbox/bin/.git-completion.bash ]; then
  . ~/Dropbox/bin/.git-completion.bash
fi


# Allow you to move hidden files
shopt -s dotglob

# Alias Definitions
alias wanip='dig +short myip.opendns.com @resolver1.opendns.com'
alias clr='clear'
alias cl='clear'
alias removeds='find . -name ".DS_Store" | xargs rm'
alias linkmysql='. ~/Dropbox/Websites/dugtools/bash/mysql_link.sh'
alias ..='cd ..'
alias wd='cd ~/Dropbox/Websites'
alias wr='cd ~/Dropbox/React'
alias drp='cd ~/Dropbox'
alias gst='git st'
alias gu='git fetch -pv --all'
alias dsh='cd ~/Dropbox/Clients/Rinck\ Advertising/Digital\ Shared/'
alias killdups='/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user;killall Finder;echo "Rebuilt Open With, relaunching Finder"'
alias ls='ls -lash'
alias ll='ls -lash'

alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias go='git checkout '
alias gk='gitk --all&'
alias gx='gitx --all'

alias got='git '
alias get='git '

# function for setting terminal titles in OSX
function title {
  printf "\033]0;%s\007" "$1"
}

function hideallfiles(){
    defaults write com.apple.finder AppleShowAllFiles -bool NO
    killall Finder
}

function showallfiles(){
    defaults write com.apple.finder AppleShowAllFiles -bool YES
    killall Finder
}

function flushdns {
    sudo dscacheutil -flushcache;sudo killall -HUP mDNSResponder; say cache flushed
}

function ptime() {
  ping "$1" | while read pong; do echo "$(date): $pong"; done
}

